import { Icon } from '@/assets/icons/icon';
import TableManager from '@/components/custom/table-manager';
import { useGetExtensions } from '@/hooks/common';
import { useCompanyFeatures } from '@/hooks/rbac';
import { useUser } from '@/hooks/use-user';
import { convertDateFormateApis } from '@/lib/utils';
import { getGroupList } from '@/services/api';
import { ColumnDef } from '@tanstack/react-table';
import { FC } from 'react';

export type LeadsTableRow = {
  _id: string;
  uuid: string;
  name: string;
  companyId: string;
  createdById: string;
  leadCount: number;
  contactDetail: any[];
  createdAt: string;
  createdByName: string;
  generatedBy: any;
  slug: string;
  groupName: string;
};
const extractCreatedByName = (
  createdById: string,
  userId: string,
  generatedBy: string,
  extensionList: any[],
  /* Contact Group's demo/API data doesn't always resolve to a known
     extension, which produced a literal "undefined undefined" — this falls
     back to a plain dash there instead. Gated behind `isLead` so the Leads
     page's existing lookup (which does always resolve) renders exactly as
     before. */
  isLead: boolean,
) => {
  const extension = extensionList?.find((item: any) => item?.uuid === createdById);
  const amI = extension?.uuid === userId;
  const name = `${extension?.first_name} ${extension?.last_name}`?.trim();
  const fallbackName = isLead ? name : extension ? name : '—';
  return (
    <div className="font-medium text-gray-900">
      {generatedBy === 'SYSTEM' ? 'Generated By System' : fallbackName}
      {amI && <span className="text-ucass-active"> (You)</span>}
    </div>
  );
};
const LeadsGroupList: FC<any> = ({
  setConfirmState,
  setDrawerState,
  isLead = true,
  onOpenContactLogs,
  search = '',
  permissionAccess = {},
  tableWrapperClassName = '',
}) => {
  const { features } = useCompanyFeatures();
  const leadsAccess = features?.plan_features?.campaign?.action || {};
  const contactAccess = features?.plan_features?.contact?.action || {};
  const actionAccess = isLead ? leadsAccess : { ...contactAccess, ...permissionAccess };
  const { user } = useUser();
  const { data: extensionList = [] } = useGetExtensions({
    page: 1,
    limit: 999999,
    filters: [],
    search: '',
    displayType: 'dropdown',
  });
  const currentUserUuid = user?.uuid || user?.user_info?.uuid || '';
  const handleNavigateToCallLogs = (data: any) => {
    onOpenContactLogs?.(data);
  };
  const columns: ColumnDef<LeadsTableRow>[] = [
    {
      header: 'Date',
      accessorKey: 'createdAt',
      cell: ({ row }) => (
        <div>{convertDateFormateApis(row?.original?.createdAt, 'MMM D, YYYY')}</div>
      ),
    },
    {
      header: 'Group Name',
      accessorKey: 'groupName',
    },
    {
      header: isLead ? 'Lead Count' : 'Contact Count',
      accessorKey: isLead ? 'leadCount' : 'contactCount',
      cell: ({ row }: { row: any }) => {
        const rawCount = isLead ? row?.original?.leadCount : row?.original?.contactCount;
        /* Contact Group's API doesn't always return `contactCount`, which left
           the badge showing nothing at all. Defaulting to 0 there only —
           gated behind `isLead` so Leads' own count keeps its exact prior
           display. */
        const count = isLead ? rawCount : (rawCount ?? 0);
        return (
          <div
            className={`flex justify-center items-center ${count > 0 ? 'cursor-pointer' : ''}`}
            onClick={() => {
              if (count <= 0) return;
              handleNavigateToCallLogs(row?.original);
            }}
          >
            <div className="inline-flex items-center justify-center min-w-6 min-h-6 px-1.5 py-0.5 text-xs font-medium text-white bg-primary rounded-full">
              {count}
            </div>
          </div>
        );
      },
      meta: {
        textAlign: 'center',
      },
    },
    {
      header: 'Created By',
      accessorKey: 'createdBy',
      cell: ({ row }: any) => {
        return extractCreatedByName(
          row?.original?.createdBy,
          currentUserUuid,
          row?.original?.generatedBy,
          extensionList,
          isLead,
        );
      },
    },
    {
      header: 'Action',
      accessorKey: 'action',
      cell: ({ row }) => {
        const group = row?.original;
        return (
          <span className="flex gap-2 items-center">
            {actionAccess?.edit && (
              <span
                onClick={() => {
                  if (group?.generatedBy === 'SYSTEM') {
                    return;
                  } else {
                    handleUpdateLeadGroup(group);
                  }
                }}

                className={` flex items-center justify-center rounded-full w-8 h-8 ${group?.generatedBy === 'SYSTEM' ? 'bg-gray-100 text-gray-500 cursor-not-allowed' : 'bg-gray-100 cursor-pointer text-gray-900 hover:bg-gray-900 hover:text-white'}`}
              >
                <Icon name="EditStrokIcon" className="w-5 h-5" />
              </span>
            )}
            {actionAccess?.delete && (
              <span
                onClick={() => {
                  if (group?.generatedBy === 'SYSTEM') {
                    return;
                  } else {
                    setConfirmState({
                      isModal: true,
                      selectedGroupId: group._id,
                    });
                  }
                }}
                className={` flex items-center justify-center rounded-full w-8 h-8 ${group?.generatedBy === 'SYSTEM' ? 'bg-gray-100 text-gray-500 cursor-not-allowed' : 'bg-red-100 cursor-pointer text-red-500 hover:bg-red-500 hover:text-white'}`}
              >
                <Icon name="TrashBin" className="w-5 h-5" />
              </span>
            )}
          </span>
        );
      },
    },
  ];
  const handleUpdateLeadGroup = (group: LeadsTableRow) => {
    setDrawerState((prev: any) => ({
      ...prev,
      addLead: true,
      selectedGroup: group,
    }));
  };

  return (
    <div className="flex w-full min-h-0 flex-1 flex-col gap-2 p-3 sm:p-4">
      <TableManager
        {...{
          columns,
          fetcherKey: 'getGroupList',
          fetcherFn: getGroupList,
          select: (response: any) => {
            const rows = response?.data?.data?.result?.rows || [];
            return rows;
          },
          extraParams: !isLead
            ? {
                generatedBy: 'COMPANY',
              }
            : { generatedBy: null },
          search,
          type: !isLead ? 'CONTACT' : 'LEAD',
          emptyTablePlaceholder: !isLead ? 'No contact groups found' : 'No leads found',
          descriptionEmptyTable: !isLead
            ? 'Add a group to start organising your contacts.'
            : 'Add or import leads to begin campaign calling.',
          customClass: tableWrapperClassName,
        }}
      />
    </div>
  );
};

export default LeadsGroupList;
